# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Teddy's Internet Domain
email: ejmartin504@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the description of Teddy's site, for all the world to see.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://teddymartin.co" # the base hostname & protocol for your site
twitter_username: ejmartin504
github_username: TeddyJMartin

# Build settings
markdown: kramdown
