# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Skeptical Technologist
email: ejmartin504@gmail.com
description: >-
  TJM's homepage
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://teddymartin.co" # the base hostname & protocol for your site
twitter_username: TeddyJMartin  
github_username: ejmartin504
github_repository: ejmartin504.github.io
linkedin_username: teddy-jerome-martin

# Build settings
markdown: kramdown
remote_theme: chesterhow/tale
plugins: 
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/